# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd12f9aec06e49f47fe9124d4771f86181c521cf6c83cb6e3d4c2127ddcc3a63c3acff34882758b7b4bcb06ff714b9bb2ca46d988d8a70ae26a8fc85bf1ac423

test:
  secret_key_base: 8bd661045ba8cba4399059d1e240c45a54772d36d0c590625bae0152708989f94d3dc6a43575ebbee920423d7ab8b9b60e2870136734f477eec078ee4aad40cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
